version: '3.7'

volumes:
  mongo-data:
    driver: local
  mgo-config:
    driver: local

services:
  mongo:
    image: mvertes/alpine-mongo:4.0.5-0
    volumes:
      - mongo-data:/data/db
      - mgo-config:/data/configdb
  redis:
    image: redis:alpine

  ui:
    image: neosapience/appname-ui:dev
    depends_on:
      - api

  api: 
    image: neosapience/appname-api:dev
    command: gunicorn --log-level=debug -k gevent
    environment:
      - SECRET_KEY_FILE=/run/secrets/api_secret
    env_file: 
      - api.env
    depends_on:
      - mongo
      - redis

  worker:
    image: neosapience/appname-api:dev
    command: celery -A task worker
    env_file: 
      - api.env
    depends_on:
      - redis

  mongo-express:
    image: mongo-express

  worker_monitor:
    image: neosapience/appname-api:dev
    command: "celery -A task flower"
    env_file: 
      - api.env
